#ifndef SHEDSIM__CONSTANTS_H
#define SHEDSIM__CONSTANTS_H 


#define BILLION 1000000000
#define SM_PID_MAX 32768

#define SIG_PROCESS_NEW SIGUSR1
#define SIG_PROCESS_END SIGUSR2

#define SM_QUANTUM_MS 200

typedef enum sm_schedulers_e {
  SM_FIRSTCOME_FIRSTSERVED = 1,
  SM_S_JOB_FIRST,
  SM_S_REMAINING_TIME_NEXT,
  SM_ROUND_ROBIN,
  SM_SCHED_WITH_PRIORITY,
  SM_RT_RIGID_DEADLINES
} sm_schedulers_e;


#endif
