#ifndef SHEDSIM__CONSTANTS_H
#define SHEDSIM__CONSTANTS_H 


#define BILLION 1000000000
#define SM_PID_MAX 32768

#define SIG_PROCESS_NEW SIGUSR1
#define SIG_PROCESS_END SIGUSR2

#define SM_QUANTUM_MS 200


#endif
